# Generated by Django 4.0.2 on 2022-04-19 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_user_blood'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='blood_given',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='cellphone',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='frequency',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='occupation',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='report',
            field=models.FileField(null=True, upload_to='documents'),
        ),
        migrations.AddField(
            model_name='user',
            name='smoke',
            field=models.BooleanField(null=True),
        ),
    ]
