# Generated by Django 4.0.2 on 2022-04-19 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_user_address_user_age_user_blood_given_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='frequency',
            field=models.CharField(choices=[('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly'), ('Once in a Year', 'Once in a Year'), ('Once in a Lifetime', 'Once in a Lifetime')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='height',
            field=models.FloatField(null=True),
        ),
    ]
