# Generated by Django 4.0.2 on 2022-04-19 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_user_frequency_alter_user_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='frequency',
            field=models.CharField(choices=[('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly'), ('Once in a Year', 'Once in a Year'), ('Once in a Lifetime', 'Once in a Lifetime')], help_text='How frequently you donate blood?', max_length=255, null=True),
        ),
    ]
